name: data100
channels:
  - defaults
dependencies:
  - attrs=18.1.0
  - beautifulsoup4=4.6.3
  - bleach=2.1.4
  - bokeh=0.13.0
  - chardet=3.0.4
  - coverage=4.5.1
  - cloudpickle=0.5.5
  - cryptography=2.3.1
  - cycler=0.10.0
  - cython=0.28.5
  - cytoolz=0.9.0.1
  - dask=0.19.0
  - dask-core=0.19.0
  - decorator=4.3.0
  - distributed=1.23.0
  - entrypoints=0.2.3
  - expat=2.2.6
  - flake8=3.5.0
  - html5lib=1.0.1
  - ipykernel=4.8.2
  - ipython=6.5.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.4.0
  - jedi=0.12.1
  - jinja2=2.10
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - markupsafe=1.0
  - matplotlib=2.2.3
  - mistune=0.8.3
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - networkx=2.1
  - notebook=5.6.0
  - numpy=1.15.1
  - numpy-base=1.15.1
  - pandas=0.23.4
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - patsy=0.5.0
  - pcre=8.42
  - pickleshare=0.7.4
  - pip=10.0.1
  - plotly=3.1.1
  - prompt_toolkit=1.0.15
  - psutil=5.4.7
  - ptyprocess=0.6.0
  - py=1.5.4
  - pygments=2.2.0
  - pyparsing=2.2.0
  - pytest=3.7.3
  - python=3.6.6
  - python-dateutil=2.7.3
  - pytz=2018.5
  - pyyaml=3.13
  - pyzmq=17.1.2
  - requests=2.19.1
  - scikit-image=0.14.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - seaborn=0.9.0
  - setuptools=40.2.0
  - simplegeneric=0.8.1
  - sip=4.19.12
  - six=1.11.0
  - sqlite=3.24.0
  - statsmodels=0.9.0
  - sympy=1.2
  - terminado=0.8.1
  - toolz=0.9.0
  - tornado=5.1
  - traitlets=4.3.2
  - widgetsnbextension=3.4.0
  - xarray=0.10.8
  - xz=5.2.4
  - zeromq=4.2.5
  - pip:
    - colorlover==0.2.1
    - cufflinks==0.13.0
    - jupyterlab==0.34.7
    - jupyterlab-launcher==0.13.1
    - oauthlib==2.1.0
    - requests-oauthlib==1.0.0
    - tweepy==3.6.0
